VEX-6030: Reduce buffer size based on heap
crunchyroll/react-native-video pull request #13
Opened 2021-11-03 23:40 UTC by gabriel-rivero

This PR changes the behavior on old devices that have poor memory management.

Jira: VEX-6030
https://jira.tenkasu.net/browse/VEX-6030

The solution implied customizing the method shouldContinueLoading from RNVLoadControl to use only the available heap, performing tests on an old Nexus 5 it was determined the ideal bytes allocation to half the reported heap, that provided some buffering during ads but smooth playback during the video with no crashes (23:39 of 23:39 at the moment of writing this, video kept playing as expected after 3 ad breaks)

The fix is only targeting Marshmallow as the reduction of buffer is substantial and other versions that work properly should not get affected.

Depending on the test result of VEX-5758, this same fix can be applied to Nougat

Reviews
Major reviewer (domain expert): @armadilio3
Minor reviewer: @jctorresM || @nickfujita

2021-11-04 09:47 UTC, nickfujita requested changes

2021-11-04 09:47 UTC, nickfujita commented on android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
> +            if (android.os.Build.VERSION.SDK_INT < android.os.Build.VERSION_CODES.N) {
Can you please move the percentage limit to a parameter of the property `bufferConfig`, called `maxHeapAllocationPercent`, and remove the hardcoded os limit?

This can be used below on line 418 in the following way:
`activityManager.getMemoryClass() * maxHeapAllocationPercent * 1024 * 1024`

This will allow us to easily modify the cases in which we apply the memory usage limit, and the amount of memory which can be used if need be.

2021-11-04 09:49 UTC, nickfujita commented on android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
> +            if (android.os.Build.VERSION.SDK_INT < android.os.Build.VERSION_CODES.N) {
This will require changes in the velocity code to apply a `0.5` value to the new `maxHeapAllocationPercent` param in the `bufferConfig` prop, only when the android os version is < N. This can be found via https://reactnative.dev/docs/platform-specific-code#detecting-the-android-version

2021-11-04 10:28 UTC, armadilio3 commented on android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
> +            if (android.os.Build.VERSION.SDK_INT < android.os.Build.VERSION_CODES.N) {
+1 on this

2021-11-04 10:30 UTC, armadilio3 commented on android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
> +            if (android.os.Build.VERSION.SDK_INT < android.os.Build.VERSION_CODES.N) {
Also do we really need it to be based on OS at all? I know that we discovered this on a specific Android version, but you can buy an extremely cheap phone with a bad implementation of Android 10 and it will also have the same problem. Maybe we can enable it for all versions since this will have no effect on devices that have enough memory to handle the buffer size and will only prevent crashes for devices that do not

2021-11-04 10:30 UTC, armadilio3 commented on android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
> +            if (android.os.Build.VERSION.SDK_INT < android.os.Build.VERSION_CODES.N) {
Or is it just that the getter method is only available on Android versions lower than N?

2021-11-04 15:59 UTC, gabriel-rivero commented on android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
> +            if (android.os.Build.VERSION.SDK_INT < android.os.Build.VERSION_CODES.N) {
got it, I'll make the changes, indeed a bad Android 10 implementation will also benefit from this change as the getter method is available from Android 5 onwards

2021-11-05 03:49 UTC, nickfujita approved these changes
Thanks for making the update. Minor looks good.

2021-11-09 17:05 UTC, armadilio3 approved these changes
Major. Great work!

2021-11-09 18:37 UTC, merged