VEX-7303: Android: Tune memory consumption to prevent libc.so crashes
crunchyroll/react-native-video pull request #35
Opened 2022-05-30 08:21 UTC by armadilio3

Add support for more memory tuning capabilities.

2022-05-30 16:48 UTC, gabriel-rivero requested changes
working as intended, documentation of the new props is needed

2022-05-30 16:48 UTC, gabriel-rivero commented on android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerViewManager.java
> +    private static final String PROP_LIMIT_MAX_RESOLUTION = "limitMaxResolution";
Please add this new props to README.md

2022-05-31 10:23 UTC, armadilio3 commented
@gabriel-rivero I added the prop to readme 👍

2022-05-31 14:06 UTC, gabriel-rivero approved these changes
major, looks good

2022-05-31 15:38 UTC, merged